/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RequestDetails;

import Business.WorkQueue.WorkRequest;
import Business.util.DateUtil;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author ketanmalik
 */
public class ViewRequest extends javax.swing.JPanel {

    /**
     * Creates new form ViewRequest
     */
    private WorkRequest wr;
    private JPanel displayPanel;
    
    public ViewRequest(JPanel displayPanel, WorkRequest wr) {
        initComponents();
        this.displayPanel = displayPanel;
        this.wr = wr;
        showDetails();
    }
    
    public void showDetails() {
        requestIdTxtBox.setText(wr.getId());
        
        try {
            receiverTxtBox.setText(wr.getReceiver().getName());
            
        } catch (Exception e) {
            receiverTxtBox.setText("");
        }
        
        statusTxtBpx.setText(wr.getStatus());
        requestDateTxtBox.setText(DateUtil.getDateToString(wr.getRequestDate()));
        try {
            resolveDateTxtBox.setText(DateUtil.getDateToString(wr.getResolveDate()));
            
        } catch (Exception e) {
            resolveDateTxtBox.setText("");
        }
        
        codeTxtBox.setText(wr.getCode() == 0 ? "" : String.valueOf(wr.getCode()));
        phoneTxtBox.setText(String.valueOf(wr.getPhoneNo()));
        medicineNameTxtBox.setText(wr.getMedicine().getName());
        strengthTxtBox.setText(String.valueOf(wr.getMedicine().getStrength()));
        descriptionTxtBox.setText(wr.getMedicine().getDescription());
        priceTxtBox.setText(String.valueOf(wr.getMedicine().getPrice()));
        marketPriceTxtBox.setText(String.valueOf(wr.getMedicine().getMarketPrice()));
        quantityTxtBox.setText(String.valueOf(wr.getMedicine().getQuantity()));
        activeIngredientTxtBox.setText(wr.getMedicine().getActiveIngredient());
        medicintTypeTxtBox.setText(wr.getMedicine().getType());
        s1TxtField.setText(wr.getMedicine().getS1());
        s2TxtField.setText(wr.getMedicine().getS2());
        r1TxtField.setText(String.valueOf(wr.getMedicine().getR1()));
        r2TxtField.setText(String.valueOf(wr.getMedicine().getR2()));
        msgTxtField.setText(wr.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        medicineNameTxtBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        strengthTxtBox = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descriptionTxtBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        requestIdTxtBox = new javax.swing.JTextField();
        priceTxtBox = new javax.swing.JTextField();
        receiverTxtBox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        statusTxtBpx = new javax.swing.JTextField();
        requestDateTxtBox = new javax.swing.JTextField();
        resolveDateTxtBox = new javax.swing.JTextField();
        codeTxtBox = new javax.swing.JTextField();
        phoneTxtBox = new javax.swing.JTextField();
        marketPriceTxtBox = new javax.swing.JTextField();
        activeIngredientTxtBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        quantityTxtBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        medicintTypeTxtBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        s1TxtField = new javax.swing.JTextField();
        s2TxtField = new javax.swing.JTextField();
        msgTxtField = new javax.swing.JTextField();
        r1TxtField = new javax.swing.JTextField();
        r2TxtField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Quantity:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Active Ingredient:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Status:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Medicine Type:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Request Date:");

        medicineNameTxtBox.setEnabled(false);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resolve Date:");

        strengthTxtBox.setEnabled(false);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Medicine Name:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pickup Code:");

        descriptionTxtBox.setEnabled(false);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone Number:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Strength:");

        requestIdTxtBox.setEnabled(false);

        priceTxtBox.setEnabled(false);

        receiverTxtBox.setEnabled(false);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Description:");

        statusTxtBpx.setEnabled(false);

        requestDateTxtBox.setEnabled(false);

        resolveDateTxtBox.setEnabled(false);

        codeTxtBox.setEnabled(false);

        phoneTxtBox.setEnabled(false);

        marketPriceTxtBox.setEnabled(false);

        activeIngredientTxtBox.setEnabled(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price:");

        quantityTxtBox.setEnabled(false);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Market Price:");

        medicintTypeTxtBox.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request ID:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Receiver:");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Work Request Details");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Substance 1:");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ratio 1:");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ratio 2:");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Substance 2:");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Message:");

        s1TxtField.setEnabled(false);
        s1TxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1TxtFieldActionPerformed(evt);
            }
        });

        s2TxtField.setEnabled(false);

        msgTxtField.setEnabled(false);

        r1TxtField.setEnabled(false);

        r2TxtField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(requestIdTxtBox, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(receiverTxtBox)
                    .addComponent(statusTxtBpx)
                    .addComponent(requestDateTxtBox)
                    .addComponent(resolveDateTxtBox)
                    .addComponent(codeTxtBox)
                    .addComponent(phoneTxtBox)
                    .addComponent(s1TxtField)
                    .addComponent(s2TxtField)
                    .addComponent(msgTxtField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(r1TxtField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(medicintTypeTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(activeIngredientTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marketPriceTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(strengthTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medicineNameTxtBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r2TxtField))
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel17)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(medicineNameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(strengthTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(descriptionTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(marketPriceTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(quantityTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(activeIngredientTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(medicintTypeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(r1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(r2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(requestIdTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(receiverTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(statusTxtBpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(requestDateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(resolveDateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(codeTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(phoneTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s1TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(s2TxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(msgTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(376, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        displayPanel.remove(this);
        Component[] componentArray = displayPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        if (userAccount.getIdentifier().equals("mp")) {
//            PatientWorkAreaJPanel pwjp = (PatientWorkAreaJPanel) component;
//            pwjp.populateTable();
//        } else {
//            DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
//            dwjp.populateTable();
//        }
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        layout.previous(displayPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void s1TxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1TxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1TxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField activeIngredientTxtBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField codeTxtBox;
    private javax.swing.JTextField descriptionTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField marketPriceTxtBox;
    private javax.swing.JTextField medicineNameTxtBox;
    private javax.swing.JTextField medicintTypeTxtBox;
    private javax.swing.JTextField msgTxtField;
    private javax.swing.JTextField phoneTxtBox;
    private javax.swing.JTextField priceTxtBox;
    private javax.swing.JTextField quantityTxtBox;
    private javax.swing.JTextField r1TxtField;
    private javax.swing.JTextField r2TxtField;
    private javax.swing.JTextField receiverTxtBox;
    private javax.swing.JTextField requestDateTxtBox;
    private javax.swing.JTextField requestIdTxtBox;
    private javax.swing.JTextField resolveDateTxtBox;
    private javax.swing.JTextField s1TxtField;
    private javax.swing.JTextField s2TxtField;
    private javax.swing.JTextField statusTxtBpx;
    private javax.swing.JTextField strengthTxtBox;
    // End of variables declaration//GEN-END:variables
}
