/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.MainJFrame;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem.EcoSystem;
import Business.EnterpriseDirectory.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UI.EcoSysAdmin.ManageEnterpriseAdmin;
import UI.EcoSysAdmin.ManageEnterprisePanel;
import UI.EcoSysAdmin.ManageNetworkPanel;
import UI.EntpAdmin.ManageEmployeeJPanel;
import UI.EntpAdmin.ManageOrganizationJPanel;
import UI.EntpAdmin.ManageUserJPanel;
import java.awt.CardLayout;
import java.awt.event.*;
import javax.swing.Timer;

/**
 *
 * @author ketanmalik
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private static UserAccount currentUser = null;
    private static Organization inOrganization = null;
    private static Enterprise inEnterprise = null;

    public MainJFrame() {
        initComponents();
        ecoSystem = dB4OUtil.retrieveSystem();
        MainJFrame.logoutBtn.setOpaque(false);
        MainJFrame.logoutBtn.setContentAreaFilled(false);
        MainJFrame.logoutBtn.setBorderPainted(false);
        showButtons(false);
        initializeSignInPanel();
    }

    public void initializeSignInPanel() {
        Timer timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                signInPanel();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

    public void signInPanel() {
        SignInPanel signInPanel = new SignInPanel(displayPanel, ecoSystem);
        CardLayout layout = (CardLayout) displayPanel.getLayout();
        displayPanel.add("signInPanel", signInPanel);
        layout.next(displayPanel);
    }

    public static void showButtons(boolean state) {
        manageNetworkBtn.setVisible(state);
        manageEnterpriseBtn.setVisible(state);
        manageAdminBtn.setVisible(state);
        logoutBtn.setVisible(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        manageNetworkBtn = new javax.swing.JButton();
        manageEnterpriseBtn = new javax.swing.JButton();
        manageAdminBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanel.setBackground(new java.awt.Color(0, 176, 226));

        manageNetworkBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        manageNetworkBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkBtn.setText("Manage Network");
        manageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkBtnActionPerformed(evt);
            }
        });

        manageEnterpriseBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        manageEnterpriseBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseBtn.setText("Manage Enterprise");
        manageEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseBtnActionPerformed(evt);
            }
        });

        manageAdminBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        manageAdminBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageAdminBtn.setText("Manage Enterprise Admin");
        manageAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Sign Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageNetworkBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageEnterpriseBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAdminBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manageNetworkBtn)
                    .addComponent(manageEnterpriseBtn)
                    .addComponent(manageAdminBtn)
                    .addComponent(logoutBtn))
                .addContainerGap())
        );

        splitPane.setTopComponent(controlPanel);

        displayPanel.setBackground(new java.awt.Color(0, 153, 153));
        displayPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(displayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        displayPanel.removeAll();
        showButtons(false);
        signInPanel();
        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void manageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkBtnActionPerformed
        if (currentUser.getIdentifier().equals("sysAdmin")) {
            ManageNetworkPanel manageNetworkPanel = new ManageNetworkPanel(displayPanel, ecoSystem, currentUser);
            displayPanel.add("manageNetworkPanel", manageNetworkPanel);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            layout.next(displayPanel);
        } else if (currentUser.getIdentifier().equalsIgnoreCase("cpadmin")
                || currentUser.getIdentifier().equalsIgnoreCase("mktadmin")) {
            ManageOrganizationJPanel mojp = new ManageOrganizationJPanel(displayPanel, currentUser, inEnterprise, inOrganization, ecoSystem, "org");
            displayPanel.add("mojp", mojp);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            layout.next(displayPanel);
        } else if (currentUser.getIdentifier().equalsIgnoreCase("mktadmin")) {
        }
    }//GEN-LAST:event_manageNetworkBtnActionPerformed

    private void manageEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseBtnActionPerformed
        if (currentUser.getIdentifier().equals("sysAdmin")) {
            ManageEnterprisePanel manageEnterprisePanel = new ManageEnterprisePanel(displayPanel, ecoSystem, currentUser);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            displayPanel.add("manageEnterprisePanel", manageEnterprisePanel);
            layout.next(displayPanel);
        } else if (currentUser.getIdentifier().equalsIgnoreCase("cpadmin")
                || currentUser.getIdentifier().equalsIgnoreCase("mktadmin")) {
            ManageEmployeeJPanel mejp = new ManageEmployeeJPanel(displayPanel, currentUser, inEnterprise, inOrganization, ecoSystem, "emp");
            displayPanel.add("mejp", mejp);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            layout.next(displayPanel);
        } else if (currentUser.getIdentifier().equalsIgnoreCase("mktadmin")) {

        }
    }//GEN-LAST:event_manageEnterpriseBtnActionPerformed

    private void manageAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminBtnActionPerformed
        if (currentUser.getIdentifier().equals("sysAdmin")) {
            ManageEnterpriseAdmin manageEnterpriseAdmin = new ManageEnterpriseAdmin(displayPanel, ecoSystem, currentUser);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            displayPanel.add("manageEnterpriseAdmin", manageEnterpriseAdmin);
            layout.next(displayPanel);
        } else if (currentUser.getIdentifier().equalsIgnoreCase("cpadmin")
                || currentUser.getIdentifier().equalsIgnoreCase("mktadmin")) {
            ManageUserJPanel mujp = new ManageUserJPanel(displayPanel, currentUser, inEnterprise, inOrganization, ecoSystem, "user");
            displayPanel.add("mujp", mujp);
            CardLayout layout = (CardLayout) displayPanel.getLayout();
            layout.next(displayPanel);
        } else if (currentUser.getIdentifier().equalsIgnoreCase("mktadmin")) {
        }
    }//GEN-LAST:event_manageAdminBtnActionPerformed

    public static Organization getInOrganization() {
        return inOrganization;
    }

    public static void setInOrganization(Organization inOrganization) {
        MainJFrame.inOrganization = inOrganization;
    }

    public static Enterprise getInEnterprise() {
        return inEnterprise;
    }

    public static void setInEnterprise(Enterprise inEnterprise) {
        MainJFrame.inEnterprise = inEnterprise;
    }

    public static UserAccount getCurrentUser() {
        return currentUser;
    }

    public static void setCurrentUser(UserAccount currentUser) {
        MainJFrame.currentUser = currentUser;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel;
    private javax.swing.JPanel displayPanel;
    public static javax.swing.JButton logoutBtn;
    public static javax.swing.JButton manageAdminBtn;
    public static javax.swing.JButton manageEnterpriseBtn;
    public static javax.swing.JButton manageNetworkBtn;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
